# .travis.yml ---
---
os: linux
dist: bionic
language: minimal
addons:
  apt:
    sources:
      - sourceline: 'ppa:kelleyk/emacs'
    packages:
      - $EMACS
env:
  - EMACS=emacs25-nox
  - EMACS=emacs26-nox
  - EMACS=emacs27-nox
before_script:
  - sudo apt-get -yq --no-install-suggests --no-install-recommends install $EMACS
script:
  - echo $EMACS
notifications:
  email: false
