# .travis.yml ---
---
os: linux
dist: bionic
language: minimal
addons:
  apt:
    sources:
      - sourceline: 'ppa:kelleyk/emacs'
env:
  - EMACS_VERSION=emacs25
  - EMACS_VERSION=emacs26
  - EMACS_VERSION=emacs27
before_install:
  - sudo apt-get -yq --no-install-suggests --no-install-recommends install $EMACS_VERSION-nox $EMACS_VERSION-el
  - sudo update-alternatives --set emacs /usr/bin/$EMACS_VERSION
  - git clone -q https://github.com/cask/cask ~/.cask
  - ln -s /usr/bin/python3 $HOME/.cask/bin/python
  - PATH=$HOME/.cask/bin:$PATH
install:
  - cask install
script:
  - emacs --version
  - make compile test
notifications:
  email: false
