# .travis.yml ---
---
os: linux
dist: bionic
language: minimal
addons:
  apt:
    sources:
      - sourceline: 'ppa:kelleyk/emacs'
env:
  - EMACS=emacs25
  - EMACS=emacs26
  - EMACS=emacs27
script:
  - echo $EMACS
notifications:
  email: false
